
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/ureka/
    register-with-eureka: false
    fetch-registry: false